# Change these first
owner: jeherve # Your GitHub organization or username, where this repository lives
repo: fedi-checks # The name of this repository

sites:
  - name: fedi.jeremy.hu
    url: https://fedi.jeremy.hu/@jeremy

status-website:
  baseUrl: /fedi-checks # where "repo" is your repository name
  name: Checking Fedi site status